--- 
admin: 
  username: admin
  password: admin
person1: 
  id: student01
  firstname: Sandra
  lastname: Cheeks
  email: goo@rsmart.com
  password: password
  type: registered
person2: 
  id: student02
  firstname: Billy
  lastname: Bob
  email: foo@rsmart.com
  password: password
  type: registered
person3: 
  id: instructor1
  firstname: Joe
  lastname: Instructor
  email: moo@rsmart.com
  password: password
  type: maintain
person4: 
  id: instructor2
  firstname: Joanne
  lastname: Instructor
  email: run@rsmart.com
  password: password
  type: maintain
person5: 
  id: student03
  firstname: Achilles
  lastname: Punks
  email: fun@rsmart.com
  password: password
  type: registered
person6: 
  id: student04
  firstname: Wilma
  lastname: Legrobach
  email: sun@rsmart.com
  password: password
  type: registered
person7: 
  id: student05
  firstname: Jason
  lastname: Elbate
  email: one@rsmart.com
  password: password
  type: registered
person8: 
  id: student06
  firstname: Jain
  lastname: Linkvence
  email: student6@rsmart.com
  password: password
  type: registered
person9: 
  id: student07
  firstname: Dirk
  lastname: Dogooder
  email: student7@rsmart.com
  password: password
  type: registered
person10: 
  id: student08
  firstname: Sally
  lastname: Manilla
  email: student8@rsmart.com
  password: password
  type: registered
person11: 
  id: student09
  firstname: Bo
  lastname: Gart
  email: student9@rsmart.com
  password: password
  type: registered
person12: 
  id: student10
  firstname: Anand
  lastname: SuperNinja
  email: stooo@rsmart.com
  password: password
  type: registered
person13: 
  id: o'gallywag
  firstname: Jack
  lastname: O'Gallywag
  email: flew@rsmart.com
  password: password
  type: registered
person14: 
  id: superman
  firstname: Clark
  lastname: Kent
  email: aheward@rsmart.com
  password: password
  type: guest
site1: 
  type: course
  name: J7ZkCWIP ]d+-fZ<| z-aL^'bU F11
  id: 312b83c4-3d6b-4a2e-a0f5-e80c9aba742d
  assignment1: "@M3T1wQKe3"
  assignment2: n.YdJfwhQ7R-MKG
  assignment3: <SCRIPT SRC=http://ha.ckers.org/xss.js?<B>
  assignment4: bitkA#@eL-h>x?:%W!`R57y4K
  assignment5: ;a6)ZC,Fh3/Vzv|K0sDE3J^%h|N"&*
  quiz1: Test 1zSK9mxZEae
  quiz2: Test 2SVxd5EzUe0
  group0: OiTj07t/f/tc:KNpj7/OdP#eJ"s-gtza!BDDilUrsHEUt\GS}J%r{K<<-8L$.w&pf->@1H58(QC`}[&uxR$" - 201111180805
  group1: "}i/\\JVLk\\*H3'Ved@XK%2069vz^6\\zqIaU@,Ui2o?:^n7'%bov`q[]\\.AK|lKV\"1RIlpoGm4AGoDC<`Tu0lW - 201111180807"
  section1: t/l@}nihx5
  section2: <A HREF="http://66.102.7.147/">XSS</A>
