--- 
admin: 
  username: admin
  password: admin
person1: 
  id: student01
  firstname: Sandra
  lastname: Cheeks
  email: goo@rsmart.com
  password: password
  type: registered
person2: 
  id: student02
  firstname: Billy
  lastname: Bob
  email: foo@rsmart.com
  password: password
  type: registered
person3: 
  id: instructor1
  firstname: Joe
  lastname: Instructor
  email: moo@rsmart.com
  password: password
  type: maintain
person4: 
  id: instructor2
  firstname: Joanne
  lastname: Instructor
  email: run@rsmart.com
  password: password
  type: maintain
person5: 
  id: student03
  firstname: Achilles
  lastname: Punks
  email: fun@rsmart.com
  password: password
  type: registered
person6: 
  id: student04
  firstname: Wilma
  lastname: Legrobach
  email: sun@rsmart.com
  password: password
  type: registered
person7: 
  id: student05
  firstname: Jason
  lastname: Elbate
  email: one@rsmart.com
  password: password
  type: registered
person8: 
  id: student06
  firstname: Jain
  lastname: Linkvence
  email: student6@rsmart.com
  password: password
  type: registered
person9: 
  id: student07
  firstname: Dirk
  lastname: Dogooder
  email: student7@rsmart.com
  password: password
  type: registered
person10: 
  id: student08
  firstname: Sally
  lastname: Manilla
  email: student8@rsmart.com
  password: password
  type: registered
person11: 
  id: student09
  firstname: Bo
  lastname: Gart
  email: student9@rsmart.com
  password: password
  type: registered
person12: 
  id: student10
  firstname: Anand
  lastname: SuperNinja
  email: stooo@rsmart.com
  password: password
  type: registered
person13: 
  id: o'gallywag
  firstname: Jack
  lastname: O'Gallywag
  email: flew@rsmart.com
  password: password
  type: registered
person14: 
  id: superman
  firstname: Clark
  lastname: Kent
  email: aheward@rsmart.com
  password: password
  type: guest
site1: 
  type: course
  name: 2&?Mx*|V ZD.?1)T= a*"JjW*z F11
  id: 5f8fd474-94d6-4c35-9cfa-56cc7e964ccb
  assignment1: Km6,@(+$dH
  assignment2: <IMG SRC="jav ascript:alert('XSS');">
  assignment3: "}eWeuqVc[y`;COI"
  assignment4: $Ir!#yO[eC;!HC^(UO7F"^3dK
  assignment5: jb84EmqMKE5ddsWPU9t3a45nauEqYY
  quiz1: Test 1xwFg4khNka
  quiz2: Test 2kn1TBcLVSt
  group0: gjj8U"$Kc,[fGFp2,Ht8,sc{!4*p0PLBZ5!0aiCL@TyS3R0[3Kd"SNpEk)a0+.oc0Z?yl4))QcD5oyJQc%4w - 201111100902
  group1: yI#^T\0Xo=i7oz^D$E<039jk9p'.Z=RO%.<YbSN?ejT|km>?/f>t:T|g0DQF{\!I!eX{zV`)kArY&^!!^0Yc - 201111100902
