--- 
admin: 
  username: admin
  password: admin
person1: 
  id: student01
  firstname: Sandra
  lastname: Cheeks
  email: goo@rsmart.com
  password: password
  type: registered
person2: 
  id: student02
  firstname: Billy
  lastname: Bob
  email: foo@rsmart.com
  password: password
  type: registered
person3: 
  id: instructor1
  firstname: Joe
  lastname: Instructor
  email: moo@rsmart.com
  password: password
  type: maintain
person4: 
  id: instructor2
  firstname: Joanne
  lastname: Instructor
  email: run@rsmart.com
  password: password
  type: maintain
person5: 
  id: student03
  firstname: Achilles
  lastname: Punks
  email: fun@rsmart.com
  password: password
  type: registered
person6: 
  id: student04
  firstname: Wilma
  lastname: Legrobach
  email: sun@rsmart.com
  password: password
  type: registered
person7: 
  id: student05
  firstname: Jason
  lastname: Elbate
  email: one@rsmart.com
  password: password
  type: registered
person8: 
  id: student06
  firstname: Jain
  lastname: Linkvence
  email: student6@rsmart.com
  password: password
  type: registered
person9: 
  id: student07
  firstname: Dirk
  lastname: Dogooder
  email: student7@rsmart.com
  password: password
  type: registered
person10: 
  id: student08
  firstname: Sally
  lastname: Manilla
  email: student8@rsmart.com
  password: password
  type: registered
person11: 
  id: student09
  firstname: Bo
  lastname: Gart
  email: student9@rsmart.com
  password: password
  type: registered
person12: 
  id: student10
  firstname: Anand
  lastname: SuperNinja
  email: stooo@rsmart.com
  password: password
  type: registered
person13: 
  id: o'gallywag
  firstname: Jack
  lastname: O'Gallywag
  email: flew@rsmart.com
  password: password
  type: registered
person14: 
  id: superman
  firstname: Clark
  lastname: Kent
  email: aheward@rsmart.com
  password: password
  type: guest
site1: 
  type: course
  name: n7e@wUMo !Vk1\2F$ g7wA*+nd F11
  id: 92406b17-6e50-4636-883b-5325bcaa0e30
  assignment1: (vR.nM?,f$
  assignment2: 5sJ0_NCP05-ywsD
  assignment3: \";alert('XSS');//
  assignment4: f=S^X`?V]}14tF\BP]6soN_zm
  assignment5: h@@u1vrYH'PsAlC?:sDiYrJdQN"?m<
  quiz1: Test 1qFhb2QYLGt
  quiz2: Test 20w0FXnhV4y
  group0: \y&ko53b":@1AFu30ji(lGSg$|:ondH-fQx0kb0{`Nf:0x*:^]sF2=p0]&;mi>]/lLn9X527Ra<A2lv!Z/55 - 201111211403
  group1: )5l2tK*BbTz=Ml$uvxzQA-(*<70?<h%w\y65Yy1B@V.J<HBAv`5X@hsZC)TvtNp4UAJu[GL&*1n,Gps@=)%< - 201111211403
  section1: t/l@}nihx5
  section2: <A HREF="http://66.102.7.147/">XSS</A>
