--- 
admin: 
  username: admin
  password: admin
person1: 
  id: student01
  firstname: Sandra
  lastname: Cheeks
  email: cswines@rsmart.com
  password: password
  type: registered
person2: 
  id: student02
  firstname: Bob
  lastname: Billy
  email: cswines@rsmart.com
  password: password
  type: registered
person3: 
  id: instructor1
  firstname: Joe
  lastname: Instructor
  email: cswines@rsmart.com
  password: password
  type: maintain
person4: 
  id: instructor2
  firstname: Joanne
  lastname: Instructor
  email: cswines@rsmart.com
  password: password
  type: maintain
person5: 
  id: student03
  firstname: Achilles
  lastname: Punks
  email: cswines@rsmart.com
  password: password
  type: registered
person6: 
  id: student04
  firstname: Wilma
  lastname: Legrobach
  email: cswines@rsmart.com
  password: password
  type: registered
person7: 
  id: student05
  firstname: Jason
  lastname: Elbate
  email: cswines@rsmart.com
  password: password
  type: registered
person8: 
  id: student06
  firstname: Jain
  lastname: Linkvence
  email: cswines@rsmart.com
  password: password
  type: registered
person9: 
  id: student07
  firstname: Dirk
  lastname: Dogooder
  email: cswines@rsmart.com
  password: password
  type: registered
person10: 
  id: student08
  firstname: Sally
  lastname: Manilla
  email: cswines@rsmart.com
  password: password
  type: registered
person11: 
  id: student09
  firstname: Bo
  lastname: Gart
  email: cswines@rsmart.com
  password: password
  type: registered
person12: 
  id: student10
  firstname: Anand
  lastname: SuperNinja
  email: cswines@rsmart.com
  password: password
  type: registered
person13: 
  id: o'gallywag
  firstname: Jack
  lastname: O'Gallywag
  email: cswines@rsmart.com
  password: password
  type: registered
person14: 
  id: superman
  firstname: Clark
  lastname: Kent
  email: aheward@rsmart.com
  password: password
  type: guest
site1: 
  type: course
  name: kx1S^L9t [snj`9K< 8\=7WU6p F11
  id: 1754ce39-7f87-4b2a-8888-9259a2ae5ae8
  assignment1: 03414889-3d24-42c2-b3e0-bcaa2eccbbbb
  assignment2: 295e1d36-baca-4bb3-81df-8f07c82c4506
  assignment3: fd22cdd9-542a-4b3f-a260-7519789c15ca
  assignment4: aa9ec25b-529d-415c-9b35-254e234c2b6a
  assignment5: f8087720-aeea-4c17-9ca3-c325580a68f4
