--- 
admin: 
  username: admin
  password: admin
person1: 
  id: student01
  firstname: Sandra
  lastname: Cheeks
  email: goo@rsmart.com
  password: password
  type: registered
person2: 
  id: student02
  firstname: Billy
  lastname: Bob
  email: foo@rsmart.com
  password: password
  type: registered
person3: 
  id: instructor1
  firstname: Joe
  lastname: Instructor
  email: moo@rsmart.com
  password: password
  type: maintain
person4: 
  id: instructor2
  firstname: Joanne
  lastname: Instructor
  email: run@rsmart.com
  password: password
  type: maintain
person5: 
  id: student03
  firstname: Achilles
  lastname: Punks
  email: fun@rsmart.com
  password: password
  type: registered
person6: 
  id: student04
  firstname: Wilma
  lastname: Legrobach
  email: sun@rsmart.com
  password: password
  type: registered
person7: 
  id: student05
  firstname: Jason
  lastname: Elbate
  email: one@rsmart.com
  password: password
  type: registered
person8: 
  id: student06
  firstname: Jain
  lastname: Linkvence
  email: student6@rsmart.com
  password: password
  type: registered
person9: 
  id: student07
  firstname: Dirk
  lastname: Dogooder
  email: student7@rsmart.com
  password: password
  type: registered
person10: 
  id: student08
  firstname: Sally
  lastname: Manilla
  email: student8@rsmart.com
  password: password
  type: registered
person11: 
  id: student09
  firstname: Bo
  lastname: Gart
  email: student9@rsmart.com
  password: password
  type: registered
person12: 
  id: student10
  firstname: Anand
  lastname: SuperNinja
  email: stooo@rsmart.com
  password: password
  type: registered
person13: 
  id: o'gallywag
  firstname: Jack
  lastname: O'Gallywag
  email: flew@rsmart.com
  password: password
  type: registered
person14: 
  id: superman
  firstname: Clark
  lastname: Kent
  email: aheward@rsmart.com
  password: password
  type: guest
site1: 
  type: course
  name: 0]HC^V"E ^=TVnInI \)<Gi*V? F11
  id: c70531de-4e68-447a-b606-e9ba418688bb
  assignment1: "@?/vi3i=ku"
  assignment2: <XSS STYLE="xss:expression(alert('XSS'))">
  assignment3: ;^kP!Gp\mZ#K7[s
  assignment4: lL\&{s.'`%Q9>Vc1%3ZDqD"rP
  assignment5: BndtP48y1pgdRcJaKb.Mg3rQSu6MGu
  quiz1: Test 1TF7CUjrsEK
  quiz2: Test 2ygGx2dWggp
  group0: $9tbm>?$k,pluw!fvm.yerv5AT_GHu4V_1Y"R,H@NFZ7SiUIxe^mV=SiuCkR_R?1:isy$nB><2tN0p{kn))= - 201111070854
  group1: vJ<NNo0d.CFbLd5>`CD>,%a\xpw3\Wy)26"Em42D.Ck#1SR*|=p:mA$2|D=Rhx{Ia}]n|S2&]gD"E?zNp":d - 201111070854
